### ISSUE TITLE
Change language [question]

### ISSUE THREAD

**Issue by pckz** [ashour/react-native-i18n-demo#2]
Thanks for your demo, has been the only one that worked for me, with react native and expo.

How can I force change the language? I tried with i18n.changeLanguage('es') but i get undefined function. Because of how it is built, (with services file that use the real library) I think I have to do something like what they do with the function "t" (src/services/i18n/index.js: 46)

Or.. Maybe is easy as I think. Thanks!!

**Comment by pckz** [comment]
I figure out that in src/services/language-detector.js the function `callback(language); ` set the language

**Comment by ashour** [comment]
Glad you got it working Xavier. Sorry completely missed the earlier notifications for some reason. Keeping rocking that sweet, sexy code man.
